config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :runs

      root to: "users#index"
    end
  get '/faq', to: 'home#faq'
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  post     'new_run' => 'runs#create'
  get      'new_run' => 'runs#new'
  
  resource :subscription, only: [:new, :create, :show, :destroy]
  resource :card, only: [:update]

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :new, :create]
  before_action :redirect_to_signup, only: [:new]

  def show
  end

  def new
    if !current_user.confirmed?
      redirect_to root_path, notice: "Please confirm your email address before subscribing."
    end

    if current_user.subscribed?
      redirect_to root_path, notice: "You already subscribed."
    end
  end

  def create

    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)
    token = params[:stripeToken]

    unless params[:stripeToken]
      return redirect_to subscription_path, flash: { error: 'No card data from Stripe. Please contact customer support.' }
    end

    customer = if current_user.stripe_id?
                Stripe::Customer.retrieve(current_user.stripe_id)
               else
                Stripe::Customer.create(email: current_user.email, source: token)
              end

    if current_user.stripe_id? && customer.default_source != token 
      Stripe::Customer.update(current_user.stripe_id, {source: token})
    end

    subscription = customer.subscriptions.create(plan: plan.id)

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
      subscribed: true,
      payment_plan: params[:plan]
    }

    options.merge!(
      card_last4: params[:user][:card_last4],
      card_exp_month: params[:user][:card_exp_month],
      card_exp_year: params[:user][:card_exp_year],
      card_brand: params[:user][:card_brand]
    ) if params[:user][:card_last4]

    options.merge!(
      free_refund_expiration_time: Time.zone.today + 31.days
    ) if !current_user.free_refund_expiration_time

    current_user.update(options)

    redirect_to root_path, notice: "Thank you for subscribing."
  end

  def destroy
    if current_user.refundable?
      charges = Stripe::Charge.list(
        customer: current_user.stripe_id,
        created: { gte: (current_user.free_refund_expiration_time - 32.days).to_i }
      )
      unless charges.count == 1 
        redirect_to root_path, flash: { error: "We're sorry. The refund was not successful. Please contact customer support." } 
      end
      charge = charges.first
      Stripe::Refund.create({charge: charge.id})
      Stripe::Subscription.retrieve(current_user.stripe_subscription_id).delete
      current_user.update(stripe_subscription_id: nil, subscribed: false)
      current_user.free_refund_expiration_time = Time.at(0)
      redirect_to root_path, notice: "Your subscription has been refunded."
    else 
      Stripe::Subscription.retrieve(current_user.stripe_subscription_id).delete
      current_user.update(stripe_subscription_id: nil, subscribed: false)
      redirect_to root_path, notice: "Your subscription has been cancelled."
    end
  
  end

  private

  def redirect_to_signup
    if !user_signed_in?
      store_location_for(:user, new_subscription_path(plan: params[:plan], plan_id: params[:plan_id]))
      redirect_to new_user_registration_path
    end
  end
end

app/views/subscriptions/new.html.erb
<div class="row">
    <div class="col-lg-5 col-md-6 ml-auto mr-auto">
      <h1 class="title">Subscribe</h1>
      <div class="container pricing">
      <h2>Chosen plan: <strong><%= params[:plan].capitalize %></strong></h2>
        <% if params[:plan] == 'monthly' %>
          <h2 class="card-title">3,99 € <small class="text-muted">/ mo</small></h2>
        <% else %>
          <h2 class="card-title">2,49 € <small class="text-muted">/ mo</small></h2>
        <% end %>
      <ul class="fa-ul checkout">
        <li><span class="fa-li"><i class="fas fa-check"></i></span>See all runs</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>Submit new runs</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>Filter runs by all categories</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>Sort deals by any category</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>Support the development and hosting of this indie website</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>30 day money back guarantee via self refund, no questions asked</li>
        <li><span class="fa-li"><i class="fas fa-check"></i></span>Tierpoints.info uses <%= link_to "Stripe", "https://stripe.com/", target: :_blank%> for secure payments and <%= link_to "does not store your credit card data", faq_path, target: :_blank %>.</li>

      </ul>
      <%= form_tag subscription_path, class: "payment-form" do |form| %>

        <div class="field checkout">
          <label for="card-element" class="label">Enter credit or debit card</label>

          <div id="card-element">
            <!-- A Stripe element will be intserted here !-->
          </div>

          <div id="card-errors" role="alert"></div>

          <%= hidden_field_tag :plan_id, params[:plan_id] %>
          <%= hidden_field_tag :plan, params[:plan] %>

          <button class="btn btn-lg btn-block btn-primary mt-2">Subscribe</button>
        </div>

      <% end %>
    </div>
  </div>
</div>
<script async src="https://js.stripe.com/v3/" id="stripe-script"></script>
<% @stripe_refresh = true %>

app/views/subscriptions/show.html.erb
<% if subscribed?%>
  <div class="row">
    <div class="col-lg-5 col-md-6 ml-auto mr-auto">
      <h1 class="title">Premium Membership</h1>
      <div class="container pricing">
        <h4> 
          <div class="row">
            <div class="col">Active plan: </div>
            <div class="col text-right"><strong><%= current_user.payment_plan.capitalize %></strong></div>
          </div>
        </h4>
        <% if current_user.payment_plan == 'monthly' %>
          <h4 class="card-title">
            <div class="row">
              <div class="col">Price:</div>
              <div class="col"><strong>3,99 € </strong><small class="text-muted">/ mo</small></div>
            </div>
          </h4>
        <% else %>
          <h4 class="card-title">
            <div class="row">
              <div class="col">Price:</div>
              <div class="col text-right"><strong>2,49 € </strong><small class="text-muted">/ mo</small></div>
            </div>
          </h4>
        <% end %>

        <h6>Current credit card:</h6>
        <div> <%= current_user.card_brand %> **** **** **** <%= current_user.card_last4 %> </div>
        <div> Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %> </div>

        <%= form_tag card_path, method: :put, class: "payment-form" do |form| %>
          <div class="field checkout mt-2">
            <div id="card-element">
              <!-- A Stripe element will be intserted here !-->
            </div>

            <div id="card-errors" role="alert"></div>

            <%= hidden_field_tag :plan_id, params[:plan_id] %>
            <%= hidden_field_tag :plan, params[:plan] %>

            <div class="btn-group-vertical btn-block">
              <button class="btn btn-primary mt-2 rounded">Update Credit Card</button>

              <% if refundable? %>
                <%= link_to 'Refund Subscription', subscription_path, class: 'btn mt-2 btn-warning rounded', data: { confirm: 'Are you sure?' }, method: :delete %>
              <% else %>
                <%= link_to 'Cancel Subscription', subscription_path, class: 'btn mt-2 btn-warning rounded', data: { confirm: 'Are you sure?' }, method: :delete %>
              <% end %>
            </div>  
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <h1 class="title">Premium Membership</h1>
  <section class="pricing">
      <div class="row">

        <!-- Free Tier -->
        <div class="col-lg-4">
          <div class="card mb-5 mb-lg-0 box-shadow subscription shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal text-center">Free</h4>
            </div>
            <div class="card-body d-flex flex-column">
              <h1 class="card-title pricing-card-title text-center mb-0">0 €</h1>
              <div>
                <h3 class="card-title text-center">
                  <small class="text-muted text-center">Free!</small>
                </h3>
              </div>

              <ul class="fa-ul">
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>See all runs</li>
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>Submit new runs</li>
              </ul>
              <% if !user_signed_in?  %>
                <%= link_to 'Sign up for free', new_user_registration_path, class: 'btn btn-block btn-lg btn-primary text-uppercase mt-auto' %>
              <% elsif !subscribed? %>
                <span class="btn btn-block btn-lg btn-outline-success mt-auto">Currently Active</span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- Yearly Tier -->
        <div class="col-lg-4">
          <div class="card mb-5 mb-lg-0 box-shadow popular subscription shadow border border-primary">
            <div class="card-header bg-primary">
              <h4 class="my-0 font-weight-normal text-center text-white">Yearly: Best Value</h4>
            </div>
            <div class="card-body d-flex flex-column">
              <h1 class="card-title pricing-card-title text-center mb-0">2,49 €</h1>
              <div>
                <h3 class="card-title text-center">
                  <small class="text-muted text-center">per month</small>
                </h3>
              </div>
              <ul class="fa-ul">
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>See all runs</li>
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>Submit new runs</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Filter runs by all categories</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Sort deals by any category</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Support the development and hosting of this indie website</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>30 day money back guarantee via self refund, no questions asked</li>
              </ul>
              <%= link_to 'Subscribe', new_subscription_path(plan: "yearly", plan_id: Rails.application.credentials.yearly), class: 'btn btn-lg btn-block mt-auto btn-primary' %>
            </div>
          </div>
        </div>
        <!-- Monthly Tier -->
        <div class="col-lg-4">
          <div class="card mb-5 mb-lg-0 box-shadow subscription shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal text-center">Monthly</h4>
            </div>
            <div class="card-body d-flex flex-column">
              <h1 class="card-title pricing-card-title text-center mb-0">3,99 €</h1>
              <div>
                <h3 class="card-title text-center">
                  <small class="text-muted text-center">per month</small>
                </h3>
              </div>
              <ul class="fa-ul">
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>See all runs</li>
                <li class="text-secondary"><span class="fa-li"><i class="fas fa-check"></i></span>Submit new runs</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Filter runs by all categories</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Sort deals by any category</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>Support the development and hosting of this indie website</li>
                <li><span class="fa-li"><i class="fas fa-check"></i></span>30 day money back guarantee via self refund, no questions asked</li>
              </ul>
              <%= link_to 'Subscribe', new_subscription_path(plan: "monthly", plan_id: Rails.application.credentials.monthly), class: 'btn btn-lg btn-block mt-auto btn-primary' %>
            </div>
          </div>
        </div>
      </div>
  </section>
<% end %>
<script async src="https://js.stripe.com/v3/" id="stripe-script"></script>
<% @stripe_refresh = true %>